#!/bin/bash

# Define reusable components
HASH="%C(yellow)%h%C(reset)"
RELATIVE_TIME="%C(green)%ar%C(reset)"
AUTHOR="%C(bold blue)%an%C(reset)"
REFS="%C(red)%d%C(reset)"
SUBJECT="%s"

# Construct formats dynamically
FORMAT="$HASH{$RELATIVE_TIME{$AUTHOR{$REFS $SUBJECT"
GRAPH_FORMAT="$HASH $RELATIVE_TIME $AUTHOR $REFS $SUBJECT"

# Check if "--graph" is passed
if [[ "$1" == "--graph" ]]; then
  shift  # Remove --graph from arguments
  git log --graph --color --pretty="format:$GRAPH_FORMAT" "$@" | less -FXRS
else
  git log --color --pretty="tformat:$FORMAT" "$@" | column -t -s '{' | less -FXRS
fi
